### ISSUE TITLE
setup script requires secure connection / cert setup for crdb 2.0+

### ISSUE THREAD

**Issue by beheerderdag** [irods/irods_database_plugin_cockroachdb#7]
I need some help with building this in Centos. 

This is my environment: 

```
[root@145 build]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@145 build]# clang++ -v
clang version 3.8.0 (https://github.com/irods/clang ad2c56e8cd2c0e39ee97bd6bde087c37118737e7) (https://github.com/irods/llvm ad5750369cc5b19f36c149f7b13151c99c7be47a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /bin
Found candidate GCC installation: /bin/../lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /bin/../lib/gcc/x86_64-redhat-linux/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /bin/../lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

[root@145 build]# which cmake
/opt/irods-externals/cmake3.5.2-0/bin/cmake
```

IRODS: 

```
[root@145 build]# rpm -qa|grep irods
irods-externals-imagemagick7.0.3-0-1.0-1.x86_64
irods-externals-cppzmq4.1-0-1.0-1.x86_64
irods-externals-epm4.2-0-1.0-1.x86_64
irods-externals-boost1.60.0-0-1.0-1.x86_64
irods-externals-clang-runtime3.8-0-1.0-1.x86_64
irods-runtime-4.2.3-1.x86_64
irods-externals-redis4.0.8-0-1.0-1.x86_64
irods-externals-autoconf5ad3567c-0-1.0-1.x86_64
irods-externals-clang3.8-0-1.0-1.x86_64
irods-externals-zeromq4-14.1.3-0-1.0-1.x86_64
irods-icommands-4.2.3-1.x86_64
irods-externals-qpid-with-proton0.34-0-1.0-1.x86_64
irods-externals-cmake3.5.2-0-1.0-1.x86_64
irods-externals-libarchive3.1.2-0-1.0-1.x86_64
irods-devel-4.2.3-1.x86_64
irods-externals-libarchive3.3.2-0-1.0-1.x86_64
irods-server-4.2.3-1.x86_64
irods-externals-libs3a30e55e8-0-1.0-1.x86_64
irods-externals-libs3f6a2098e-0-1.0-1.x86_64
irods-externals-json3.0.1-0-1.0-1.x86_64
irods-externals-avro1.7.7-0-1.0-1.x86_64
irods-externals-jansson2.7-0-1.0-1.x86_64
```

Build the package: 

```
[root@145 build]# ninja-build package
[1/11] Building CXX object CMakeFiles/cockroachdb.dir/src/general_query.cpp.o
FAILED: CMakeFiles/cockroachdb.dir/src/general_query.cpp.o 
/bin/clang++   -DBOOST_SYSTEM_NO_DEPRECATED -DENABLE_RE -Dcockroachdb_EXPORTS -I/include/c++/v1 -I/usr/include/irods -I/usr/include/postgresql -I../include -I/include -fPIC   -nostdinc++ -std=c++14 -Wno-write-strings -MMD -MT CMakeFiles/cockroachdb.dir/src/general_query.cpp.o -MF CMakeFiles/cockroachdb.dir/src/general_query.cpp.o.d -o CMakeFiles/cockroachdb.dir/src/general_query.cpp.o -c ../src/general_query.cpp
In file included from ../src/general_query.cpp:27:
In file included from /usr/include/irods/icatHighLevelRoutines.hpp:15:
In file included from /usr/include/irods/irods_resource_manager.hpp:6:
In file included from /usr/include/irods/irods_resource_plugin.hpp:5:
In file included from /usr/include/irods/irods_plugin_base.hpp:14:
In file included from /usr/include/irods/irods_re_plugin.hpp:4:
/usr/include/irods/irods_load_plugin.hpp:57:21: error: no matching member function for call to 'append'
        plugin_home.append(_type);
        ~~~~~~~~~~~~^~~~~~
/usr/include/boost/filesystem/path.hpp:315:11: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    path& append(InputIterator begin, InputIterator end)
          ^
/usr/include/boost/filesystem/path.hpp:689:15: note: candidate function template not viable: requires 3 arguments, but 1 was provided
  path& path::append(InputIterator begin, InputIterator end, const codecvt_type& cvt)
              ^
/usr/include/boost/filesystem/path.hpp:703:15: note: candidate function template not viable: requires 2 arguments, but 1 was provided
  path& path::append(Source const& source, const codecvt_type& cvt)
              ^
/usr/include/boost/filesystem/path.hpp:305:11: note: candidate function not viable: requires 2 arguments, but 1 was provided
    path& append(const value_type* ptr, const codecvt_type&)  // required in case ptr overlaps *this
          ^
1 error generated.
[2/11] Building CXX object CMakeFiles/cockroachdb.dir/src/db_plugin.cpp.o
FAILED: CMakeFiles/cockroachdb.dir/src/db_plugin.cpp.o 
/bin/clang++   -DBOOST_SYSTEM_NO_DEPRECATED -DENABLE_RE -Dcockroachdb_EXPORTS -I/include/c++/v1 -I/usr/include/irods -I/usr/include/postgresql -I../include -I/include -fPIC   -nostdinc++ -std=c++14 -Wno-write-strings -MMD -MT CMakeFiles/cockroachdb.dir/src/db_plugin.cpp.o -MF CMakeFiles/cockroachdb.dir/src/db_plugin.cpp.o.d -o CMakeFiles/cockroachdb.dir/src/db_plugin.cpp.o -c ../src/db_plugin.cpp
In file included from ../src/db_plugin.cpp:9:
In file included from /usr/include/irods/icatHighLevelRoutines.hpp:15:
In file included from /usr/include/irods/irods_resource_manager.hpp:6:
In file included from /usr/include/irods/irods_resource_plugin.hpp:5:
In file included from /usr/include/irods/irods_plugin_base.hpp:14:
In file included from /usr/include/irods/irods_re_plugin.hpp:4:
/usr/include/irods/irods_load_plugin.hpp:57:21: error: no matching member function for call to 'append'
        plugin_home.append(_type);
        ~~~~~~~~~~~~^~~~~~
/usr/include/boost/filesystem/path.hpp:315:11: note: candidate function template not viable: requires 2 arguments, but 1 was provided
    path& append(InputIterator begin, InputIterator end)
          ^
/usr/include/boost/filesystem/path.hpp:689:15: note: candidate function template not viable: requires 3 arguments, but 1 was provided
  path& path::append(InputIterator begin, InputIterator end, const codecvt_type& cvt)
              ^
/usr/include/boost/filesystem/path.hpp:703:15: note: candidate function template not viable: requires 2 arguments, but 1 was provided
  path& path::append(Source const& source, const codecvt_type& cvt)
              ^
/usr/include/boost/filesystem/path.hpp:305:11: note: candidate function not viable: requires 2 arguments, but 1 was provided
    path& append(const value_type* ptr, const codecvt_type&)  // required in case ptr overlaps *this
          ^
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by trel** [comment]
Your build errors could stem from using the system clang which was not compiled with a new enough boost (possibly 1.48?)... the irods-externals boost is at 1.60 at the moment:
```
$ rpm -qa | grep irods
irods-externals-jansson2.7-0-1.0-1.x86_64
irods-runtime-4.2.3-1.x86_64
irods-devel-4.2.3-1.x86_64
irods-externals-cmake3.5.2-0-1.0-1.x86_64
irods-externals-clang3.8-0-1.0-1.x86_64
irods-externals-avro1.7.7-0-1.0-1.x86_64
irods-externals-zeromq4-14.1.3-0-1.0-1.x86_64
irods-externals-clang-runtime3.8-0-1.0-1.x86_64
irods-externals-libarchive3.3.2-0-1.0-1.x86_64
irods-icommands-4.2.3-1.x86_64
irods-api-plugin-bulkreg-common-4.2.3-1.x86_64
irods-externals-boost1.60.0-0-1.0-1.x86_64
irods-server-4.2.3-1.x86_64

$ rpm -qa | grep ODBC
unixODBC-2.3.1-11.el7.x86_64
unixODBC-devel-2.3.1-11.el7.x86_64

$ which cmake
/opt/irods-externals/cmake3.5.2-0/bin/cmake
```

In both the api plugin as well as the database plugin, I needed to drop the targeted iRODS version to 4.2.3 (these are unreleased, and so currently pointing to the master branch, aka 4.3.0):
```
$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8e78889..2210b01 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,6 @@
 cmake_minimum_required(VERSION 3.5.0 FATAL_ERROR) #CPACK_DEBIAN_<COMPONENT>_PACKAGE_NAME
 
-find_package(IRODS 4.3.0 REQUIRED)
+find_package(IRODS 4.2.3 REQUIRED)
 
 set(CMAKE_C_COMPILER ${IRODS_EXTERNALS_FULLPATH_CLANG}/bin/clang)
 set(CMAKE_CXX_COMPILER ${IRODS_EXTERNALS_FULLPATH_CLANG}/bin/clang++)
```

Then, both plugins compiled and installed.

Note that cockroachdb 2.0 now requires a secure connection from a non-root client, so you must deploy with certificates if using the 'irods' database username.

**Comment by beheerderdag** [comment]
I am building against 4.2.3 and also didn't install any system clang so using the iRODS one. 
```
[root@145 irods_database_plugin_cockroachdb]# which cmake
/opt/irods-externals/cmake3.5.2-0/bin/cmake
```
The bulk reg api plugin installed file but not the cockroachdb plugin. I will give this another closer look.

**Comment by beheerderdag** [comment]
Thanks for pointing to boost. I removed the system one. I think that was the problem. 
I did get some errors with ninja but using just make worked. I will try to document the process to what I missed. 

```
[root@145 irods_database_plugin_cockroachdb]# make
[ 10%] Building CXX object CMakeFiles/cockroachdb.dir/src/db_plugin.cpp.o
[ 20%] Building CXX object CMakeFiles/cockroachdb.dir/src/general_query.cpp.o
[ 30%] Building CXX object CMakeFiles/cockroachdb.dir/src/general_query_setup.cpp.o
[ 40%] Building CXX object CMakeFiles/cockroachdb.dir/src/general_update.cpp.o
[ 50%] Building CXX object CMakeFiles/cockroachdb.dir/src/irods_catalog_properties.cpp.o
[ 60%] Building CXX object CMakeFiles/cockroachdb.dir/src/irods_sql_logger.cpp.o
[ 70%] Building CXX object CMakeFiles/cockroachdb.dir/src/low_level_libpq.cpp.o
[ 80%] Building CXX object CMakeFiles/cockroachdb.dir/src/mid_level_routines.cpp.o
[ 90%] Linking CXX shared library libcockroachdb.so
[ 90%] Built target cockroachdb
Scanning dependencies of target IRODS_PHONY_TARGET_icatSysTables_cockroachdb.sql
[100%] Generating icatSysTables_cockroachdb.sql
[100%] Built target IRODS_PHONY_TARGET_icatSysTables_cockroachdb.sql
```

**Comment by trel** [comment]
ah, very good.

**Comment by beheerderdag** [comment]
I will work on documenting my steps but I want to get the plugin up and running.  I have the plugins installed (I see ```/usr/lib/irods/plugins/database/libcockroachdb.so```). 

I confirmed that cockroachdb is running (with cert). 

```
[root@145 ~]# cockroach node status --certs-dir=certs
+----+-----------------+--------+---------------------+---------------------+---------+
| id |     address     | build  |     updated_at      |     started_at      | is_live |
+----+-----------------+--------+---------------------+---------------------+---------+
|  1 | localhost:26257 | v2.0.3 | 2018-07-18 07:12:55 | 2018-07-18 06:48:45 | true    |
+----+-----------------+--------+---------------------+---------------------+---------+
```
I can login via the sql command line as the irods user: 
```
[root@145 ~]# cockroach sql --certs-dir=certs --user=irods 
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
Enter password: 
# Server version: CockroachDB CCL v2.0.3 (x86_64-unknown-linux-gnu, built 2018/06/18 16:11:33, go1.10) (same version as client)
# Cluster ID: c0764e63-3bbd-463f-8343-5b6ace5170c1
#
# Enter \? for a brief introduction.
#
warning: no current database set. Use SET database = <dbname> to change, CREATE DATABASE to make a new database.
irods@:26257/> show databases;
+----------+
| Database |
+----------+
| icat     |
+----------+
(1 row)
```

Then I run the setup script and get this: 

```
-------------------------------------------
Database Type: cockroachdb
ODBC Driver:   cockroachdb
Database Host: localhost
Database Port: 26257
Database Name: icat
Database User: irods
-------------------------------------------

Please confirm [yes]: yes
Database password: 
Updating /etc/irods/server_config.json...
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 436, in main
    setup_server(irods_config, json_configuration_file=options.json_configuration_file)
  File "/var/lib/irods/scripts/setup_irods.py", line 115, in setup_server
    database_interface.setup_database_config(irods_config)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 165, in setup_database_config
    if database_already_in_use_by_irods(irods_config):
  File "/var/lib/irods/scripts/irods/database_interface.py", line 73, in database_already_in_use_by_irods
    with contextlib.closing(database_connect.get_database_connection(irods_config)) as connection:
  File "/var/lib/irods/scripts/irods/database_connect.py", line 213, in get_database_connection
    sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/database_connect.py", line 194, in get_database_connection
    return pypyodbc.connect(connection_string.encode('ascii'), ansi=True, autocommit = True)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 2452, in __init__
    self.connect(connectString, autocommit, ansi, timeout, unicode_results, readonly)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 2501, in connect
    check_success(self, ret)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 988, in check_success
    ctrl_err(SQL_HANDLE_DBC, ODBC_obj.dbc_h, ret, ODBC_obj.ansi)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 964, in ctrl_err
    raise Error(state,err_text)
IrodsError: pypyodbc encountered an error connecting to the database:
('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified')
Exiting...


```

the odbc.ini looks like this 

```
root@145 ~]# cat /var/lib/irods/.odbc.ini 
[iRODS Catalog]
Driver=cockroachdb
Description=iRODS Catalog
Trace=No
Database=icat
TraceFile=
Servername=localhost
FakeOidIndex=No
ShowOidColumn=No
RowVersioning=No
CommLog=0
ReadOnly=No
Debug=0
ConnSettings=
Port=26257
Ksqo=0
ShowSystemTables=No
```

and in server_config.json I see: 

```
   "database": {
            "cockroachdb": {
                "db_host": "localhost", 
                "db_name": "icat", 
                "db_odbc_driver": "cockroachdb", 
                "db_password": "irods", 
                "db_port": 26257, 
                "db_username": "irods"
            }
        }, 

```

**Comment by beheerderdag** [comment]
Giving this another try .....

Do I need to select 'PostgreSQL' here? I was typing in 'cockroachdb'. 

```
+-----------------------------------------+
| Configuring the database communications |
+-----------------------------------------+

You are configuring an iRODS database plugin. The iRODS server cannot be started until its database has been properly configured.

ODBC driver for cockroachdb [PostgreSQL]: 

```

I selected the default PostgreSQL then it was missing ```/usr/lib64/psqlodbcw.so```.  I needed to install postgresql-odbc. After that I run the setup again and I get this: (I am running cockroachdb in secure mode with a cert dir). I used the guide here https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html


```
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 988, in check_success
    ctrl_err(SQL_HANDLE_DBC, ODBC_obj.dbc_h, ret, ODBC_obj.ansi)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 966, in ctrl_err
    raise DatabaseError(state,err_text)
IrodsError: pypyodbc encountered an error connecting to the database:
('08P01', '[08P01] [unixODBC]ERROR: node is running secure mode, SSL connection required')
```

I also tried with the insecure mode in cockroachdb and the root user but still cannot establish the connection. In insecure mode you cannot create a database user with password so I guess that won't work.

**Comment by trel** [comment]
Okay - I hit that as well.  We have used the current setup script when talking to 1.x.

We're working on making sure the cert configuration is available and used by the plugin when talking to a 2.0 crdb.

**Comment by xu-hao** [comment]
In insecure mode, you can create a database user, it will simply accept any password. So if you run in insecure mode you can just pass in any password, and it should work.

**Comment by beheerderdag** [comment]
ok. thanks for the clarification. Yes, that method worked. My setup script worked now in the insecure mode. 

```
root@:26257/icat> show tables;
+-------------------------+
|          Table          |
+-------------------------+
| r_coll_main             |
| r_data_main             |
| r_grid_configuration    |
| r_meta_main             |
| r_microsrvc_main        |
| r_microsrvc_ver         |
| r_objectid              |
| r_objt_access           

...

```

**Comment by JustinKyleJames** [comment]
That is good to hear.  I have only done this with insecure mode as well.  We are looking into how this can be done in secure mode.

**Comment by JustinKyleJames** [comment]
Just an update.  If you want to test secure mode you can do the following:


1.  Create the certificates as described here.  https://www.cockroachlabs.com/docs/stable/create-security-certificates.html

2.  Create the irods user and put the certificates in ~irods/.cockroach-certs/


$ ls .cockroach-certs

ca.crt  client.irods.crt  client.irods.key

3.  Update /var/lib/irods/scripts/irods/database_connect.py and add the part in red within get_connection_string():

def get_connection_string(db_config, irods_config):
    odbc_dict = {}
    odbc_dict['Password'] = db_config['db_password']
    odbc_dict['PWD'] = db_config['db_password']
    odbc_dict['Username'] = db_config['db_username']
    odbc_dict['User'] = db_config['db_username']
    odbc_dict['UID'] = db_config['db_username']
    odbc_dict['sslkey'] = '/var/lib/irods/.cockroach-certs/client.irods.key'
    odbc_dict['sslcert'] = '/var/lib/irods/.cockroach-certs/client.irods.crt'
    odbc_dict['sslrootcert'] = '/var/lib/irods/.cockroach-certs/ca.crt'
    odbc_dict['sslmode'] = 'require'
    odbc_dict['ssl'] = 'true'

4.  Run the setup script and it should work.


We are in the process of updating the setup scripts to prompt for this information.





________________________________

**Comment by JustinKyleJames** [comment]
Just an update.  If you want to test secure mode you can do the following:


1.  Create the certificates as described here.  https://www.cockroachlabs.com/docs/stable/create-security-certificates.html

2.  Create the irods user and put the certificates in ~irods/.cockroach-certs/

```
$ ls .cockroach-certs

ca.crt  client.irods.crt  client.irods.key
```

3.  Update /var/lib/irods/scripts/irods/database_connect.py and add the last five lines below within get_connection_string():

```
def get_connection_string(db_config, irods_config):
    odbc_dict = {}
    odbc_dict['Password'] = db_config['db_password']
    odbc_dict['PWD'] = db_config['db_password']
    odbc_dict['Username'] = db_config['db_username']
    odbc_dict['User'] = db_config['db_username']
    odbc_dict['UID'] = db_config['db_username']
    odbc_dict['sslkey'] = '/var/lib/irods/.cockroach-certs/client.irods.key'
    odbc_dict['sslcert'] = '/var/lib/irods/.cockroach-certs/client.irods.crt'
    odbc_dict['sslrootcert'] = '/var/lib/irods/.cockroach-certs/ca.crt'
    odbc_dict['sslmode'] = 'require'
    odbc_dict['ssl'] = 'true'
```

4.  Run the setup script and it should work.


We are in the process of updating the setup scripts to prompt for this information.

**Comment by beheerderdag** [comment]
Thanks for the update. I made the changes and was able to use secure mode now.

**Comment by JustinKyleJames** [comment]
After doing some more testing, you can make this run without the sslkey and sslcert parameters.  This will just force the login to use a password which iRODS does already.  The ca.crt file can be located anywhere as long as it is world readable so the irods user does not have to be created ahead of time.

Here's an example of the configuration which was tested and worked.  In this case I just put the ca cert in /tmp/ca.crt.


```
def get_connection_string(db_config, irods_config):
    odbc_dict = {}
    odbc_dict['Password'] = db_config['db_password']
    odbc_dict['PWD'] = db_config['db_password']
    odbc_dict['Username'] = db_config['db_username']
    odbc_dict['User'] = db_config['db_username']
    odbc_dict['UID'] = db_config['db_username']
    odbc_dict['sslrootcert'] = '/tmp/ca.crt'
    odbc_dict['sslmode'] = 'require'
    odbc_dict['ssl'] = 'true'
```
